FROM python:3.11.9

WORKDIR /src

COPY requirements.txt ./requirements.txt
COPY results ./results
COPY Uploads ./Uploads
COPY sort_alg.py ./sort_alg.py
COPY sort.py ./sort.py
COPY mask.png ./mask.png
COPY type.css ./type.css

RUN pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install libgl1 -y

EXPOSE 8080

CMD ["streamlit", "run", "sort_alg.py"]

